server:
  port: 8093

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池管理配置
dynamic:
  thread:
    pool:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # redis host
        host: 127.0.0.1
        # redis port
        port: 6379

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: a00510c4-c973-4179-961e-dd500a1c350d
        group: DEFAULT_GROUP
        data-id: dynamic-thread-pool-test-app-dev.yaml
        file-extension: yaml
        import-check:
          enabled: false
        extension-configs:
          - data-id: dynamic-thread-pool-test-app-dev.yaml
            group: DEFAULT_GROUP
            refresh: true


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
